//
//  VisitorBarChartInteractorTests.swift
//  VisitorApp
//
//  Created by Mayur Kamthe on 22/10/20.
//  Copyright (c) 2020 Mayur Kamthe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import VisitorApp
import XCTest

class VisitorBarChartInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: VisitorBarChartInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupVisitorBarChartInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupVisitorBarChartInteractor()
  {
    sut = VisitorBarChartInteractor()
  }
  
  // MARK: Test doubles
  
  class VisitorBarChartPresentationLogicSpy: VisitorBarChartPresentationLogic
  {
   
    var presentChartDataCalled = false
    
    func presentVisitorBarChartData(response: VisitorBarChart.VisitorBarChartData.Response) {
        presentChartDataCalled = true
    }
  }
  
  // MARK: Tests
  
  func testBarChartData()
  {
    // Given
    let spy = VisitorBarChartPresentationLogicSpy()
    sut.presenter = spy
    let request = VisitorBarChart.VisitorBarChartData.Request()
    
    // When
    sut.visitorBarChartData(request: request)
    
    // Then
    XCTAssertTrue(spy.presentChartDataCalled, "VisitorBarChartData(request:) should ask the presenter to format the result")
  }
}
